apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask-jwt-auth-web
resources:
- kubernetes/flexigym-angular-app-deployment.yaml
- kubernetes/flexigym-angular-app-service.yaml
