apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-angular-app
  name: flexigym-angular-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 4200
  type: LoadBalancer
  loadBalancerIP: 35.198.220.113
  selector:
    io.kompose.service: flexigym-angular-app
status:
  loadBalancer: {}
