apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-subscribe-api
  name: flexigym-subscribe-api
spec:
  ports:
  - name: "6200"
    port: 6200
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 35.198.220.113
  selector:
    io.kompose.service: flexigym-subscribe-api
status:
  loadBalancer:
    ingress:
    - ip: 35.198.220.113
