apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-advertise-api
  name: flexigym-advertise-api
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 34.87.6.16
  selector:
    io.kompose.service: flexigym-advertise-api
status:
  loadBalancer: {}
