apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-advertise-service2
  name: flexigym-advertise-service2
spec:
  type: NodePort
  ports:
  - name: "9100"
    port: 9100
    targetPort: 5000
  selector:
    io.kompose.service: flexigym-advertise-service2
