apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-advertise-service
  name: flexigym-advertise-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flexigym-advertise-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: flexigym-advertise-service
    spec:
      containers:
      - image: asia.gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: "Always"
        name: flexigym-advertise-service
        ports:
        - containerPort: 4996
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
